name: Docker
on:
  push:
    branches: 
      - main
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo apt install cpu-checker
          kvm-ok
          
      - name: Run docker image
        run: |
          docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Nexus 5" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_13.0

      - name: Check device
        run: |
          adb devices
