name: Docker
on:
  push:
    branches: 
      - main_w
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run docker image
      - run: |
        docker run -d -p 6080:6080 -e EMULATOR_DEVICE="Samsung Galaxy S10" -e WEB_VNC=true --device /dev/kvm --name android-container budtmo/docker-android:emulator_11.0
